// Photos are stored in public/assets/photos (sources and licences in CREDITS.txt there).
const photo = (name) => `/assets/photos/${name}.jpg`;

export const slides = [
  { id: 'kenya', tone: '#8a4529', src: photo('hero-kenya'), placeholder: 'Maasai Mara at sunset', place: 'Maasai Mara, Kenya', title: 'The Great Migration', line: 'Private conservancy camps, dawn game drives and sundowners on the open savannah.' },
  { id: 'indonesia', tone: '#1d5b66', src: photo('hero-indonesia'), placeholder: 'Raja Ampat islands', place: 'Raja Ampat, Indonesia', title: 'Islands of Raja Ampat', line: 'Limestone karsts and turquoise lagoons, explored by private boat.' },
  { id: 'kerala', tone: '#3f6b3a', src: photo('hero-kerala'), placeholder: 'Wooden boats on the Kerala backwaters at sunrise', place: 'Western Ghats & Vembanad, Kerala', title: 'The Spice Frontier & Backwaters', line: 'Misty colonial tea trails in the Western Ghats, then silent skiff voyages across Vembanad.' },
  { id: 'northeast', tone: '#2f5a44', src: photo('hero-northeast'), placeholder: 'Dzukou Valley, Northeast India', place: 'Nagaland & Manipur, Northeast India', title: 'Dzükou Valley', line: 'Rolling green hills, living root bridges and quiet homestays across the Northeast.' },
];

export const itineraries = [
  { id: 'kenya', src: photo('itin-kenya'), placeholder: 'Maasai Mara landscape', kicker: '8 Nights · Kenya', title: 'Safari in the Maasai Mara', body: 'Nairobi, then private conservancy camps in the Mara with game drives, bush walks and a balloon flight at sunrise.', story: ["Dawn on the Mara arrives slowly: first a grey hush over the grass, then the low call of a lion somewhere beyond the camp, then light spilling gold across the plains. You drink coffee wrapped in a blanket as the guide reads the morning in tracks and birdsong, and there is nowhere you need to be.", "Days follow the rhythm of the animals rather than a clock. Long, quiet drives with the engine off. A walk with a Maasai elder who names every plant underfoot. Evenings by the fire under a sky so dark the stars feel close enough to touch."] },
  { id: 'indonesia', src: photo('itin-indonesia'), placeholder: 'Mount Bromo at sunrise', kicker: '10 Nights · Indonesia', title: 'Java Volcanoes to Raja Ampat', body: 'Sunrise over Mount Bromo, then days at sea among the islands of Raja Ampat.', story: ["You climb in darkness, breath clouding, and wait at the rim as Bromo slowly takes shape below: a smoking caldera rising from a sea of mist while the sky turns from violet to rose. It is cold, and silent, and entirely unforgettable.", "Then the world turns to water. In Raja Ampat, days drift between limestone islands and lagoons the colour of glass. You swim off the side of the boat, eat fish grilled on a deserted beach, and fall asleep to nothing but the sound of the tide."] },
  { id: 'kerala', src: photo('itin-kerala'), placeholder: 'A houseboat on the Alleppey backwaters', kicker: '6 Nights · Kerala', title: 'The Spice Frontier & Backwaters', body: 'Misty colonial tea trails in the Western Ghats, followed by silent skiff voyages through secluded Vembanad waters.', story: ["In the Western Ghats, mornings begin in cloud. Tea terraces fold down the hillside in endless green, pickers call softly between the rows, and the air smells of cardamom and wet earth. You walk old estate trails with a planter whose family has worked these slopes for generations.", "Below, Vembanad moves at the pace of a paddle. A slim wooden skiff carries you through narrow canals where kingfishers flash blue and village life unfolds along the banks: washing on the steps, a temple bell, children waving. Nothing here is hurried, and soon neither are you."] },
  { id: 'northeast', src: photo('itin-northeast'), placeholder: 'Living root bridges, Meghalaya', kicker: '9 Nights · Meghalaya & Nagaland', title: 'Hills of the Northeast', body: 'Shillong, the living root bridges of Cherrapunji and the Dzükou Valley trek.', story: ["Shillong wakes to pine-scented mist and the sound of rain on tin roofs. Down in the Khasi hills, you cross living root bridges, grown by hand over generations, as the river runs clear and fast beneath your feet.", "Further east, the trail to Dzükou climbs through bamboo into a valley of soft, rolling green that seems to go on forever. Nights are spent in family homestays, sharing smoked meats and stories by the hearth, welcomed less as a guest than as someone returning."] },
];

export const stays = [
  { id: 'amanpuri', src: photo('stay-amanpuri'), placeholder: 'Amanpuri pavilion', place: 'Phuket, Thailand', name: 'Amanpuri', body: 'Pavilions set in a coconut grove above Pansea Beach on the Andaman Sea.', story: ["Morning comes softly through the coconut palms: a band of light on the teak floor, the hush of the Andaman Sea far below, a breeze that carries salt and frangipani. You walk barefoot along shaded paths to Pansea Beach, and the day seems to wait for you to decide what it will be.", "Time here is measured in small pleasures. A swim before anyone else is awake. Lunch in the shade with your feet in the sand. Evenings on your pavilion terrace as the sky turns from coral to indigo, with nothing to do but watch it."] },
  { id: 'al-maha', src: photo('stay-al-maha'), placeholder: 'Al Maha dunes', place: 'Dubai Desert Conservation Reserve', name: 'Al Maha, a Luxury Collection Desert Resort', body: 'Private pool suites facing open dunes, with oryx and gazelle roaming the reserve.', story: ["In the desert, silence has a texture. You wake before sunrise to watch the dunes turn from grey to rose to gold, and from your private pool an oryx lifts its head on the ridge, unbothered and utterly still.", "Days move to the rhythm of the sand and the light. A camel ride along the crest of a dune, a falconry display as the heat softens, dinner beneath a sky so clear it feels as if the stars have come closer. The world feels far away, and that is the point."] },
  { id: 'mandapa', src: photo('stay-mandapa'), placeholder: 'Mandapa river villas', place: 'Ubud, Bali, Indonesia', name: 'Mandapa, a Ritz-Carlton Reserve', body: 'Riverside villas among terraced rice paddies in the Ayung River valley.', story: ["Below Ubud, the Ayung River runs fast and green through the valley, and Mandapa sits beside it among terraced rice paddies that farmers still tend by hand. You wake to running water, birdsong and the scent of incense from a small morning offering.", "Days unfold gently: a walk through the paddies with the farmer who works them, a blessing at the village temple, long hours by your villa pool. As evening falls, the valley fills with the sound of frogs and the glow of lanterns along the river."] },
];
